name: flutter_flavor_gen_core
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  analyzer: ^5.10.0
  args: ^2.4.0
  async: ^2.10.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  mason_logger: ^0.2.5
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  pedantic_mono: ^1.21.1
  test: ^1.21.0
