name: flutter_flavor_gen
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

executables:
  flutter_flavor_gen: flutter_flavor_gen

# dependencies:
#   path: ^1.8.0

dependencies:
  flutter_flavor_gen_core: 0.0.1
  # args: ^2.4.0

dev_dependencies:
  pedantic_mono: ^1.21.1
  test: ^1.21.0
